#!/bin/bash

# ════════════════════════════════════════════════════════════════
# ИНСТРУКЦИЯ: Как подтянуть WiFi файлы на ваш Mac
# ════════════════════════════════════════════════════════════════

echo "Выполните эти команды в вашем терминале на Mac:"
echo ""
echo "1. Перейдите в папку проекта:"
echo ""
echo "   cd ~/Desktop/DDDD/TRiANGL-Native-iOS"
echo ""
echo "2. Проверьте текущую ветку:"
echo ""
echo "   git branch"
echo ""
echo "3. Переключитесь на ветку с WiFi функционалом:"
echo ""
echo "   git checkout claude/scan-wifi-devices-JP3V2"
echo ""
echo "4. Подтяните последние изменения с GitHub:"
echo ""
echo "   git pull origin claude/scan-wifi-devices-JP3V2"
echo ""
echo "5. Проверьте что файлы появились:"
echo ""
echo "   ls -la TRiANGL/TRiANGL/WiFi*.swift"
echo ""
echo "6. Откройте Finder в этой папке:"
echo ""
echo "   open TRiANGL/TRiANGL"
echo ""
echo "Теперь вы должны видеть все 8 WiFi файлов!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "АЛЬТЕРНАТИВА: Если ветки нет локально, создайте её:"
echo ""
echo "   git fetch origin"
echo "   git checkout -b claude/scan-wifi-devices-JP3V2 origin/claude/scan-wifi-devices-JP3V2"
echo "   ls -la TRiANGL/TRiANGL/WiFi*.swift"
echo ""
